FORMAT: 1A
HOST: http://eop.soshace.com

# Eye-of-Providence

EoP is a service which helps you manage your team. In general, the first version is an aggregator of time-tracking systems. Eye of providence can fetch time-entries form services e.g. Redmine or Upwork and shows all data in one place. Service is very helpful for managers or teamleaders.

### Installation
First of all you should clone files from the git, then create .env file in root folder. Here is sample configuration:

    MONGO_URL = mongodb://localhost/eop
    COLLECTION = eop
    PORT = 5000
    SESSION_SECRET = secret
    MAIL_USERNAME = bot@gmail.com
    MAIL_PASS = password

Install all modules via npm

    npm install

Run webpack 

    webpack

Start an application

    npm start

## TimeEntries Collection [/api/timeEntryBatch]

### Get Batches for a user- about 20 items [GET]

+ Response 200 (application/json)

        [
            {
                "_id": "5800949f5ac8ca30a2e5db29",
                "redmineTimeEntryId": 1378,
                "entrySource": "redmine",
                "duration": 165,
                "description": "Prototype for reports page is done, understanding and planning also are done",
                "executor": "max-buranbaev",
                "number": 2585,
                "__v": 0,
                "dateCreated": "2016-10-14T08:03:23.000Z",
                "date": "2016-10-14T08:03:23.000Z"
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }