FORMAT: 1A
HOST: http://eop.soshace.com

# Eye-of-Providence

EoP is a service which helps you manage your team. In general, the first version is an aggregator of time-tracking systems. Eye of providence can fetch time-entries form services e.g. Redmine or Upwork and shows all data in one place. Service is very helpful for managers or teamleaders.

## Time-entry batch [/api/timeEntryBatch]

### Get Batches for a user- about 20 items [GET]

+ Response 200 (application/json)

        [
            {
                "_id": "5800949f5ac8ca30a2e5db29",
                "redmineTimeEntryId": 1378,
                "entrySource": "redmine",
                "duration": 165,
                "description": "Prototype for reports page is done, understanding and planning also are done",
                "executor": "max-buranbaev",
                "number": 2585,
                "__v": 0,
                "dateCreated": "2016-10-14T08:03:23.000Z",
                "date": "2016-10-14T08:03:23.000Z"
            }
        ]

## Adding a new time-entry [/api/timeEntry/add]

### Create a new time-entry [POST]

You may create new time-entry, just send object with time-entry.

+ Request (application/json)

        {
            "entrySource": "eop",
            "duration": 165,
            "description": "My sample time-entry",
            "executor": "57e8d0c84bb4a29392c72316",
            "dateCreated": 1476689842494
        }

+ Response 200 (application/json)

        {
            "__v":0,
            "entrySource":"eop",
            "duration":0.00275,
            "description":
            "My sample time-entry",
            "executor":"57e8d0c84bb4a29392c72316",
            "_id":"5804801a34065e509ef893ad",
            "dateCreated":"2016-10-17T07:37:22.494Z",
            "date":"2016-10-17T07:39:06.827Z"
        }
        
## Changing & deleting the time-entry [/api/timeEntry/5804801a34065e509ef893ad]

### Delete a time-entry [DELETE]

+ Response 200 (application/json)
 

        {
            "message":"Time entry successfully deleted",
            "timeEntryId":"58047fb234065e509ef89385"
        }

        
### Change a time-entry [PUT]

+ Request (application/json)

        {
            "entrySource": "eop",
            "duration": 167,
            "description": "My changed time-entry",
            "executor": "57e8d0c84bb4a29392c72316",
            "dateCreated": 1476689842494
        }

+ Response 200 (application/json)

        {
            "__v":1,
            "entrySource":"eop",
            "duration":0.00275,
            "description":
            "My changed time-entry",
            "executor":"57e8d0c84bb4a29392c72316",
            "_id":"5804801a34065e509ef893ad",
            "dateCreated":"2016-10-17T07:37:22.494Z",
            "date":"2016-10-17T07:39:06.827Z"
        }

## Sync with redmine [/api/sync/redmine]

### Syncing task for autorized user [GET]
    
+ Response 200 (application/json)

        [
            {
                "_id": "5800949f5ac8ca30a2e5db29",
                "redmineTimeEntryId": 1378,
                "entrySource": "redmine",
                "duration": 165,
                "description": "Prototype for reports page is done, understanding and planning also are done",
                "executor": "max-buranbaev",
                "number": 2585,
                "__v": 0,
                "dateCreated": "2016-10-14T08:03:23.000Z",
                "date": "2016-10-14T08:03:23.000Z"
            }
        ]